using System.Globalization;
using System.Text;

namespace ApiSmith.Config;

/// <summary>Writes apismith.yaml. Deterministic field order; never writes secrets.</summary>
public static class YamlWriter
{
    public static string Write(ApiSmithConfig config)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# Generated by apismith. Re-run with `apismith new --config apismith.yaml`.");

        WriteScalar(sb, "apiVersion", config.ApiVersion switch
        {
            ApiVersion.V1 => "v1",
            ApiVersion.V2 => "v2",
            _ => throw new System.InvalidOperationException($"Unsupported ApiVersion: {config.ApiVersion}"),
        });
        WriteScalar(sb, "projectName", config.ProjectName);
        WriteScalar(sb, "outputDirectory", config.OutputDirectory);
        WriteScalar(sb, "targetFramework", config.TargetFramework);
        WriteScalar(sb, "endpointStyle", config.EndpointStyle.ToString());
        WriteScalar(sb, "architecture", config.Architecture.ToString());
        WriteScalar(sb, "dataAccess", config.DataAccess.ToString());
        WriteScalar(sb, "auth", config.Auth.ToString());
        WriteScalar(sb, "versioning", config.Versioning.ToString());
        WriteBool(sb, "generateInitialMigration", config.GenerateInitialMigration);
        WriteBool(sb, "includeTestsProject", config.IncludeTestsProject);
        WriteBool(sb, "includeDockerAssets", config.IncludeDockerAssets);
        WriteBool(sb, "validateForeignKeyReferences", config.ValidateForeignKeyReferences);
        WriteBool(sb, "emitRepositoryInterfaces", config.EmitRepositoryInterfaces);
        WriteBool(sb, "partitionStoredProceduresBySchema", config.PartitionStoredProceduresBySchema);

        WriteCrud(sb, config.Crud);
        WriteList(sb, "schemas", config.Schemas);

        sb.AppendLine("# Connection strings are NEVER written to apismith.yaml. Supply one via:");
        sb.AppendLine("#   --connection \"Server=...;Database=...;...\"");
        sb.AppendLine("#   or the APISMITH_CONNECTION environment variable.");

        return sb.ToString();
    }

    private static void WriteScalar(StringBuilder sb, string key, string value)
    {
        if (NeedsQuoting(value))
        {
            sb.AppendLine($"{key}: \"{Escape(value)}\"");
        }
        else
        {
            sb.AppendLine($"{key}: {value}");
        }
    }

    private static void WriteBool(StringBuilder sb, string key, bool value) =>
        sb.AppendLine($"{key}: {(value ? "true" : "false")}");

    private static void WriteCrud(StringBuilder sb, CrudOperations ops)
    {
        var names = new List<string>();
        if (ops.HasFlag(CrudOperations.GetList)) { names.Add("GetList"); }
        if (ops.HasFlag(CrudOperations.GetById)) { names.Add("GetById"); }
        if (ops.HasFlag(CrudOperations.Post))    { names.Add("Post");    }
        if (ops.HasFlag(CrudOperations.Put))     { names.Add("Put");     }
        if (ops.HasFlag(CrudOperations.Patch))   { names.Add("Patch");   }
        if (ops.HasFlag(CrudOperations.Delete))  { names.Add("Delete");  }

        if (names.Count == 0)
        {
            sb.AppendLine("crud: []");
        }
        else
        {
            sb.AppendLine("crud:");
            foreach (var name in names)
            {
                sb.AppendLine($"  - {name}");
            }
        }
    }

    private static void WriteList(StringBuilder sb, string key, List<string> values)
    {
        if (values.Count == 0)
        {
            sb.AppendLine($"{key}: []");
            return;
        }

        sb.AppendLine($"{key}:");
        foreach (var v in values.OrderBy(s => s, System.StringComparer.Ordinal))
        {
            sb.AppendLine($"  - {(NeedsQuoting(v) ? "\"" + Escape(v) + "\"" : v)}");
        }
    }

    private static bool NeedsQuoting(string value)
    {
        if (value.Length == 0)
        {
            return true;
        }

        foreach (var c in value)
        {
            if (c is ':' or '#' or '-' or '[' or ']' or '{' or '}' or ',' or '&' or '*' or '!' or '|' or '>' or '\'' or '"' or '%' or '@' or '`')
            {
                return true;
            }

            if (char.IsWhiteSpace(c) && c != ' ')
            {
                return true;
            }
        }

        if (char.IsWhiteSpace(value[0]) || char.IsWhiteSpace(value[^1]))
        {
            return true;
        }

        return bool.TryParse(value, out _) || double.TryParse(value, NumberStyles.Any, CultureInfo.InvariantCulture, out _);
    }

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
