using ApiSmith.Config;
using ApiSmith.Core.Pipeline;
using ApiSmith.Generation.Architectures;

namespace ApiSmith.Generation.Emitters;

public static class RepoHygieneEmitter
{
    public static IEnumerable<EmittedFile> Emit(ApiSmithConfig config, IArchitectureLayout layout)
    {
        yield return new EmittedFile(layout.GitignorePath(), GitignoreContent);
        yield return new EmittedFile(layout.EditorconfigPath(), EditorConfigContent);
        yield return new EmittedFile(layout.ReadmePath(), BuildReadme(config, layout));
    }

    private const string GitignoreContent = """
        bin/
        obj/
        *.user
        *.suo
        .vs/
        .vscode/
        .idea/

        TestResults/
        coverage*

        appsettings.Development.json
        appsettings.Local.json
        *.local.json

        .DS_Store
        Thumbs.db
        """;

    private const string EditorConfigContent = """
        root = true

        [*]
        charset = utf-8
        end_of_line = lf
        indent_style = space
        indent_size = 4
        insert_final_newline = true
        trim_trailing_whitespace = true

        [*.{json,csproj,props,targets,sln}]
        indent_size = 2

        [*.cs]
        csharp_using_directive_placement = outside_namespace:warning
        csharp_style_namespace_declarations = file_scoped:warning
        csharp_prefer_braces = when_multiline:warning
        """;

    private static string BuildReadme(ApiSmithConfig config, IArchitectureLayout layout) => $$"""
        # {{config.ProjectName}}

        Generated by [ApiSmith](https://github.com/art/apismith).

        ## Run

        ```
        dotnet run --project src/{{MainProjectFolder(config, layout)}}
        ```

        Open the Scalar UI at `https://localhost:5001/scalar/v1`.

        ## Configure the database

        Set `ConnectionStrings:DefaultConnection` in `appsettings.json`, or override:

        ```
        dotnet user-secrets set "ConnectionStrings:DefaultConnection" "Server=...;Database=...;..."
        ```

        ## Add filtering, paging, and sorting

        Every list endpoint exposes its base `IQueryable<TEntity>` at the marked
        extension point — chain `.Where(...)`, `.OrderBy(...)`, `.Skip/Take` directly.

        {{layout.LayoutDescription(config)}}

        ## Re-generate

        Edit `apismith.yaml` and re-run `apismith new --config apismith.yaml`.
        """;

    private static string MainProjectFolder(ApiSmithConfig config, IArchitectureLayout layout)
    {
        var webProject = layout.Projects(config).First(p => p.IsWebProject);
        return System.IO.Path.GetFileName(System.IO.Path.GetDirectoryName(webProject.RelativeCsprojPath)!)!;
    }
}
